use axum::{
    extract::{ws::WebSocket, Query, State, WebSocketUpgrade},
    http::StatusCode,
    response::{Html, IntoResponse, Json},
};
use futures_util::{SinkExt, StreamExt};
use rand::Rng;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::{mpsc, RwLock};
use tokio::time::Instant;
use validator::Validate;

use crate::AppState;

// Characters for pairing codes — no ambiguous chars (0/O, 1/I/L excluded)
const CODE_CHARS: &[u8] = b"ABCDEFGHJKMNPQRSTUVWXYZ23456789";

/// Room expiry: 10 minutes if unpaired.
const ROOM_EXPIRY_SECS: u64 = 600;

/// WebSocket ping interval in seconds.
/// Keeps idle connections alive across NAT firewalls without high bandwidth overhead.
/// At 100k connections, 60s pings produce ~1700 tiny frames/sec (~10KB/s total) — negligible.
const WS_PING_INTERVAL_SECS: u64 = 60;

// --- Types ---

struct PairRoom {
    #[allow(dead_code)]
    code: String,
    hostname: String,
    /// One sender per connected Atem, keyed by atem_id.
    /// Multiple Atems can be connected to the same room simultaneously.
    atem_txs: HashMap<String, mpsc::UnboundedSender<String>>,
    astation_tx: Option<mpsc::UnboundedSender<String>>,
    created_at: Instant,
}

#[derive(Clone)]
pub struct RelayHub {
    rooms: Arc<RwLock<HashMap<String, PairRoom>>>,
}

impl RelayHub {
    pub fn new() -> Self {
        Self {
            rooms: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    /// Remove rooms that are older than ROOM_EXPIRY_SECS and have no astation connected.
    pub async fn cleanup_expired(&self) {
        let now = Instant::now();
        let mut rooms = self.rooms.write().await;
        rooms.retain(|_, room| {
            let age = now.duration_since(room.created_at).as_secs();
            // Keep if not expired, or if astation is connected (actively paired)
            age < ROOM_EXPIRY_SECS || room.astation_tx.is_some()
        });
    }
}

impl Default for RelayHub {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate an 8-char pairing code like "ABCD-EFGH" (no ambiguous chars).
fn generate_pairing_code() -> String {
    let mut rng = rand::thread_rng();
    let chars: Vec<u8> = (0..8)
        .map(|_| CODE_CHARS[rng.gen_range(0..CODE_CHARS.len())])
        .collect();
    let s = String::from_utf8(chars).unwrap();
    format!("{}-{}", &s[..4], &s[4..])
}

// --- Request / Response types ---

#[derive(Deserialize, Validate)]
pub struct CreatePairRequest {
    #[validate(length(min = 1, max = 255))]
    pub hostname: String,
}

#[derive(Serialize, Deserialize)]
pub struct CreatePairResponse {
    pub code: String,
}

#[derive(Serialize, Deserialize)]
pub struct PairStatusResponse {
    pub paired: bool,
    pub hostname: String,
    /// Number of Atems currently connected (0 = none). For backward compat,
    /// `atem_connected` is derived as `atem_count > 0`.
    pub atem_count: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub atem_ids: Option<Vec<String>>,
    pub atem_connected: bool,
    pub astation_connected: bool,
    pub expired: bool,
}

#[derive(Serialize)]
pub struct DeletePairResponse {
    pub closed: bool,
}

#[derive(Deserialize)]
pub struct WsQuery {
    // Pairing-based auth (traditional)
    pub role: Option<String>,
    pub code: Option<String>,
    // Session-based auth (after HTTP auth)
    pub session: Option<String>,
    // Atem identity — stable ID used to distinguish multiple Atems in the same room.
    // Typically the Atem's hostname. Auto-generated by the relay if not provided.
    pub atem_id: Option<String>,
}

#[derive(Deserialize)]
pub struct PairPageQuery {
    pub code: String,
}

// --- Handlers ---

/// POST /api/pair — Register for pairing, get a code back.
pub async fn create_pair_handler(
    State(state): State<AppState>,
    Json(body): Json<CreatePairRequest>,
) -> impl IntoResponse {
    // Validate input
    if let Err(e) = body.validate() {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({"error": format!("Validation error: {}", e)})),
        )
            .into_response();
    }

    let hub = &state.relay;
    let code = generate_pairing_code();
    let room = PairRoom {
        code: code.clone(),
        hostname: body.hostname,
        atem_txs: HashMap::new(),
        astation_tx: None,
        created_at: Instant::now(),
    };

    let mut rooms = hub.rooms.write().await;
    rooms.insert(code.clone(), room);
    drop(rooms);

    tracing::info!("Pair room created: {}", code);
    (StatusCode::CREATED, Json(CreatePairResponse { code })).into_response()
}

/// GET /api/pair/:code — Check pairing status.
pub async fn pair_status_handler(
    State(state): State<AppState>,
    axum::extract::Path(code): axum::extract::Path<String>,
) -> impl IntoResponse {
    let rooms = state.relay.rooms.read().await;
    match rooms.get(&code) {
        Some(room) => {
            let atem_count = room.atem_txs.len();
            let atem_connected = atem_count > 0;
            let astation_connected = room.astation_tx.is_some();
            let paired = atem_connected && astation_connected;
            let age = Instant::now().duration_since(room.created_at).as_secs();
            let expired = !astation_connected && age >= ROOM_EXPIRY_SECS;
            let atem_ids = if atem_count > 0 {
                Some(room.atem_txs.keys().cloned().collect())
            } else {
                None
            };
            Ok(Json(PairStatusResponse {
                paired,
                hostname: room.hostname.clone(),
                atem_count,
                atem_ids,
                atem_connected,
                astation_connected,
                expired,
            }))
        }
        None => Err((
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({"error": "Room not found"})),
        )),
    }
}

/// DELETE /api/pair/:code — Close a pairing room.
/// Removes the room, disconnecting both sides.
pub async fn delete_pair_handler(
    State(state): State<AppState>,
    axum::extract::Path(code): axum::extract::Path<String>,
) -> impl IntoResponse {
    let mut rooms = state.relay.rooms.write().await;
    if rooms.remove(&code).is_some() {
        tracing::info!("Pair room closed by client: {}", code);
        (StatusCode::OK, Json(DeletePairResponse { closed: true })).into_response()
    } else {
        (StatusCode::NOT_FOUND, Json(serde_json::json!({"error": "Room not found"}))).into_response()
    }
}

/// GET /ws — WebSocket upgrade for relay.
/// Auth methods:
///   1. Pairing: ?role=atem|astation&code=XXXX (short-lived, explicit approval)
///   2. Session: ?session=<session_id> (after HTTP auth, longer-lived)
pub async fn ws_handler(
    State(state): State<AppState>,
    Query(params): Query<WsQuery>,
    ws: WebSocketUpgrade,
) -> impl IntoResponse {
    let hub = state.relay.clone();

    // Session-based auth (hybrid flow)
    if let Some(session_id) = params.session.clone() {
        // Validate session
        let session = state.sessions.get(&session_id).await;
        match session {
            Some(s) if s.status == crate::auth::SessionStatus::Granted => {
                // Valid session - use session_id as room code, role defaults to "atem"
                let code = format!("session-{}", session_id);
                let role = params.role.clone().unwrap_or_else(|| "atem".to_string());

                // Create room if it doesn't exist
                {
                    let mut rooms = hub.rooms.write().await;
                    if !rooms.contains_key(&code) {
                        rooms.insert(
                            code.clone(),
                            PairRoom {
                                code: code.clone(),
                                hostname: s.hostname.clone(),
                                atem_txs: HashMap::new(),
                                astation_tx: None,
                                created_at: Instant::now(),
                            },
                        );
                    }
                }

                let atem_id = params.atem_id.clone().unwrap_or_else(|| "session-atem".to_string());
                return ws.on_upgrade(move |socket| handle_ws(hub, code, role, atem_id, socket))
                    .into_response();
            }
            _ => {
                return (StatusCode::UNAUTHORIZED, "Invalid or expired session").into_response();
            }
        }
    }

    // Pairing-based auth (traditional flow)
    let code = match params.code.clone() {
        Some(c) => c,
        None => return (StatusCode::BAD_REQUEST, "Missing code or session parameter").into_response(),
    };
    let role = match params.role.clone() {
        Some(r) => r,
        None => return (StatusCode::BAD_REQUEST, "Missing role parameter").into_response(),
    };

    // For astation: auto-create identity room if it doesn't exist (allows persistent relay rooms).
    // For atem/other: verify the room exists and has not expired.
    if role == "astation" {
        let mut rooms = hub.rooms.write().await;
        rooms.entry(code.clone()).or_insert_with(|| {
            tracing::info!("Auto-creating identity room for code={}", &code[..code.len().min(16)]);
            PairRoom {
                code: code.clone(),
                hostname: "identity".to_string(),
                atem_txs: HashMap::new(),
                astation_tx: None,
                created_at: Instant::now(),
            }
        });
    } else {
        let rooms = hub.rooms.read().await;
        match rooms.get(&code) {
            None => return (StatusCode::NOT_FOUND, "Room not found").into_response(),
            Some(room) => {
                // If room is expired (no astation and older than limit), reject with 410 Gone
                if room.astation_tx.is_none() {
                    let age = Instant::now().duration_since(room.created_at).as_secs();
                    if age >= ROOM_EXPIRY_SECS {
                        return (StatusCode::GONE, "Pairing code has expired").into_response();
                    }
                }
            }
        }
    }

    // Sanitize atem_id to URL-safe chars (hostname may contain spaces or special chars)
    let atem_id = params.atem_id
        .as_deref()
        .map(|s| s.chars().filter(|c| c.is_alphanumeric() || *c == '-' || *c == '_' || *c == '.').collect::<String>())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| format!("atem-{:x}", rand::thread_rng().gen::<u32>()));

    ws.on_upgrade(move |socket| handle_ws(hub, code, role, atem_id, socket))
        .into_response()
}

/// Message routing protocol for multi-Atem rooms:
///
/// Atem → Astation:  relay WRAPS  `{"atem_id":"<id>","payload":<original_msg>}`
/// Astation → Atem:  Astation sends `{"atem_id":"<id>","payload":<msg>}` → relay UNWRAPS, routes to that Atem
/// Astation → ALL:   Astation sends raw JSON (no `atem_id` key) → relay BROADCASTS to every Atem in the room
async fn handle_ws(hub: RelayHub, code: String, role: String, atem_id: String, socket: WebSocket) {
    let (mut ws_sink, mut ws_stream) = socket.split();
    let (tx, mut rx) = mpsc::unbounded_channel::<String>();

    // Register this side's sender in the room
    {
        let mut rooms = hub.rooms.write().await;
        let room = match rooms.get_mut(&code) {
            Some(r) => r,
            None => {
                tracing::warn!("Room {} disappeared before WS setup", code);
                return;
            }
        };

        match role.as_str() {
            "atem" => {
                room.atem_txs.insert(atem_id.clone(), tx.clone());
            }
            "astation" => {
                room.astation_tx = Some(tx.clone());
            }
            _ => {
                tracing::warn!("Unknown role: {}", role);
                return;
            }
        }
    };

    tracing::info!("WS connected: role={} code={}", role, code);

    // Task: forward messages from our channel to the WS sink, with periodic pings
    // for NAT keepalive. URLSession (macOS) and tungstenite (Atem) both auto-respond
    // to server pings with pong — no client changes needed.
    let code_for_writer = code.clone();
    let write_task = tokio::spawn(async move {
        let mut ping_interval = tokio::time::interval(
            std::time::Duration::from_secs(WS_PING_INTERVAL_SECS)
        );
        ping_interval.tick().await; // skip the immediate first tick
        loop {
            tokio::select! {
                msg = rx.recv() => {
                    match msg {
                        Some(text) => {
                            if ws_sink
                                .send(axum::extract::ws::Message::Text(text.into()))
                                .await
                                .is_err()
                            {
                                tracing::debug!("WS write failed for {}", code_for_writer);
                                break;
                            }
                        }
                        None => break, // channel closed
                    }
                }
                _ = ping_interval.tick() => {
                    if ws_sink
                        .send(axum::extract::ws::Message::Ping(Vec::new()))
                        .await
                        .is_err()
                    {
                        tracing::debug!("WS ping failed for {} — removing dead connection", code_for_writer);
                        break;
                    }
                }
            }
        }
    });

    // Read incoming frames and forward to the other side.
    // A 90s idle timeout ensures dead connections (no pong response to our 60s ping)
    // are detected and cleaned up within 90s rather than waiting for the OS TCP timeout.
    //
    // Routing rules (see handle_ws comment above for full protocol spec):
    //  - Atem → relay: raw msg → relay wraps {"atem_id":id,"payload":msg} → Astation
    //  - Astation → relay:
    //      {"atem_id":"x","payload":msg}  → unwrap, forward payload to Atem "x"
    //      raw msg (no atem_id)           → broadcast payload to ALL Atems in room
    let hub_for_read = hub.clone();
    let role_for_read = role.clone();
    let code_for_read = code.clone();
    let atem_id_for_read = atem_id.clone();
    let read_timeout = std::time::Duration::from_secs(WS_PING_INTERVAL_SECS + 30);
    loop {
        let msg_result = match tokio::time::timeout(read_timeout, ws_stream.next()).await {
            Ok(Some(msg)) => msg,
            Ok(None) => break, // stream ended
            Err(_) => {
                tracing::debug!("WS idle timeout for {} {} — no frame in {}s", role, code_for_read, WS_PING_INTERVAL_SECS + 30);
                break;
            }
        };
        match msg_result {
            Ok(axum::extract::ws::Message::Text(text)) => {
                match role_for_read.as_str() {
                    "atem" => {
                        // Wrap with atem_id so Astation knows which Atem sent the message
                        let astation_tx = {
                            let rooms = hub_for_read.rooms.read().await;
                            rooms.get(&code_for_read).and_then(|r| r.astation_tx.clone())
                        };
                        if let Some(tx) = astation_tx {
                            // Parse payload as JSON value so serde handles escaping correctly
                            let envelope = if let Ok(payload) = serde_json::from_str::<serde_json::Value>(&text) {
                                serde_json::json!({"atem_id": atem_id_for_read, "payload": payload}).to_string()
                            } else {
                                // Fallback: treat as raw string payload
                                serde_json::json!({"atem_id": atem_id_for_read, "payload": text}).to_string()
                            };
                            let _ = tx.send(envelope);
                        }
                    }
                    "astation" => {
                        // Parse envelope: {"atem_id":"x","payload":{...}} → route to Atem x
                        // Or raw JSON (no atem_id) → broadcast to all Atems
                        if let Ok(env) = serde_json::from_str::<serde_json::Value>(&text) {
                            if let Some(target_id) = env.get("atem_id").and_then(|v| v.as_str()) {
                                // Targeted: route payload to the specific Atem
                                let payload = env.get("payload").cloned().unwrap_or(serde_json::Value::Null);
                                let payload_str = payload.to_string();
                                let target_tx = {
                                    let rooms = hub_for_read.rooms.read().await;
                                    rooms.get(&code_for_read)
                                        .and_then(|r| r.atem_txs.get(target_id).cloned())
                                };
                                if let Some(tx) = target_tx {
                                    let _ = tx.send(payload_str);
                                }
                            } else {
                                // Broadcast: send raw message to all Atems
                                let txs: Vec<_> = {
                                    let rooms = hub_for_read.rooms.read().await;
                                    rooms.get(&code_for_read)
                                        .map(|r| r.atem_txs.values().cloned().collect())
                                        .unwrap_or_default()
                                };
                                for tx in txs {
                                    let _ = tx.send(text.to_string());
                                }
                            }
                        }
                    }
                    _ => {}
                }
            }
            Ok(axum::extract::ws::Message::Close(_)) => break,
            Ok(axum::extract::ws::Message::Pong(_)) => {} // expected response to our Ping
            Err(e) => {
                tracing::debug!("WS read error for {} {}: {}", role, code_for_read, e);
                break;
            }
            _ => {}
        }
    }

    // Cleanup: remove our sender from the room
    {
        let mut rooms = hub_for_read.rooms.write().await;
        if let Some(room) = rooms.get_mut(&code) {
            match role.as_str() {
                "atem" => { room.atem_txs.remove(&atem_id); }
                "astation" => { room.astation_tx = None; }
                _ => {}
            }
            // Remove the room only when all sides have disconnected
            if room.atem_txs.is_empty() && room.astation_tx.is_none() {
                rooms.remove(&code);
                tracing::info!("Room {} removed (all sides disconnected)", code);
            }
        }
    }

    write_task.abort();
    tracing::info!("WS disconnected: role={} code={}", role, code);
}

/// GET /pair?code=XXXX — HTML landing page for pairing.
pub async fn pair_page_handler(
    State(state): State<AppState>,
    Query(params): Query<PairPageQuery>,
) -> impl IntoResponse {
    let (hostname, initial_status) = {
        let rooms = state.relay.rooms.read().await;
        match rooms.get(&params.code) {
            Some(room) => {
                let age = Instant::now().duration_since(room.created_at).as_secs();
                let expired = room.astation_tx.is_none() && age >= ROOM_EXPIRY_SECS;
                let status = InitialPageStatus {
                    atem_connected: !room.atem_txs.is_empty(),
                    astation_connected: room.astation_tx.is_some(),
                    expired,
                };
                (room.hostname.clone(), status)
            }
            None => {
                return (
                    StatusCode::NOT_FOUND,
                    Html("<h1>Pairing code not found</h1><p>The code may have expired.</p>".to_string()),
                ).into_response()
            }
        }
    };
    let html = render_pair_page(&params.code, &hostname, &initial_status);
    Html(html).into_response()
}

struct InitialPageStatus {
    atem_connected: bool,
    astation_connected: bool,
    expired: bool,
}

/// HTML-escape a string to prevent XSS attacks
fn html_escape(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '&' => "&amp;".to_string(),
            '<' => "&lt;".to_string(),
            '>' => "&gt;".to_string(),
            '"' => "&quot;".to_string(),
            '\'' => "&#x27;".to_string(),
            '/' => "&#x2F;".to_string(),
            _ => c.to_string(),
        })
        .collect()
}

fn render_pair_page(code: &str, hostname: &str, status: &InitialPageStatus) -> String {
    let code_esc = html_escape(code);
    let hostname_esc = html_escape(hostname);
    let code_url = urlencoding::encode(code);
    // Initial state classes for JS
    let atem_dot = if status.atem_connected { "dot connected" } else { "dot" };
    let astation_dot = if status.astation_connected { "dot connected" } else { "dot" };
    let expired_class = if status.expired { " expired" } else { "" };

    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Atem Pairing — {code}</title>
  <style>
    *{{box-sizing:border-box;margin:0;padding:0}}
    body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;background:#0a0a0a;color:#e0e0e0}}
    .card{{background:#1a1a2e;border-radius:16px;padding:40px 48px;text-align:center;width:100%;max-width:440px;box-shadow:0 8px 32px rgba(0,0,0,.4);transition:opacity .4s}}
    .card.expired{{opacity:.45;pointer-events:none}}
    h2{{font-size:20px;color:#fff;margin-bottom:6px}}
    .sub{{font-size:14px;color:#888;margin-bottom:4px}}
    .code{{font-size:46px;font-weight:700;letter-spacing:5px;color:#00d4aa;margin:20px 0;font-family:'SF Mono',monospace}}
    .hostname{{font-size:13px;color:#555;margin-bottom:28px}}
    .btn{{display:inline-block;padding:11px 30px;background:#00d4aa;color:#0a0a0a;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;transition:background .2s}}
    .btn:hover{{background:#00f5c4}}
    .btn-close{{display:inline-block;padding:11px 30px;background:#2a1a1a;color:#ff6b6b;border:1px solid #ff6b6b44;border-radius:8px;font-weight:600;font-size:15px;cursor:pointer;transition:all .2s}}
    .btn-close:hover{{background:#ff6b6b22}}
    .status-row{{display:flex;justify-content:center;gap:24px;margin-top:28px;font-size:13px;color:#666}}
    .dot{{width:8px;height:8px;border-radius:50%;background:#333;display:inline-block;margin-right:6px;transition:background .3s}}
    .dot.connected{{background:#00d4aa;box-shadow:0 0 6px #00d4aa88}}
    .info-box{{background:#0f1a14;border:1px solid #00d4aa33;border-radius:10px;padding:16px;margin:20px 0;font-size:13px;text-align:left}}
    .info-row{{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px solid #ffffff08}}
    .info-row:last-child{{border-bottom:none}}
    .info-label{{color:#666}}
    .info-value{{color:#ccc;font-family:'SF Mono',monospace;font-size:12px}}
    .success-icon{{font-size:36px;margin-bottom:12px}}
    .download{{margin-top:20px;font-size:13px;color:#444}}
    .download a{{color:#00d4aa;text-decoration:none}}
    #expired-msg{{color:#ff6b6b;font-size:14px;margin-top:12px;display:none}}
    #closed-msg{{color:#888;font-size:14px;margin-top:12px;display:none}}
    #view-waiting,#view-paired{{display:none}}
  </style>
</head>
<body>
  <div class="card{expired_class}" id="card">
    <div id="view-waiting">
      <h2>Atem Pairing</h2>
      <p class="sub">Open in Astation to connect</p>
      <div class="code">{code}</div>
      <div class="hostname">Host: {hostname}</div>
      <a class="btn" href="astation://pair?code={code_url}">Open in Astation</a>
      <div id="expired-msg">⏱ This pairing code has expired.</div>
      <div class="download"><p>No Astation? <a href="https://github.com/AgoraIO-Community/astation/releases">Download</a></p></div>
    </div>

    <div id="view-paired">
      <div class="success-icon">🔗</div>
      <h2>Connected!</h2>
      <p class="sub" style="margin-bottom:16px">Atem and Astation are paired via relay</p>
      <div class="info-box">
        <div class="info-row"><span class="info-label">Atem host</span><span class="info-value" id="paired-hostname">—</span></div>
        <div class="info-row"><span class="info-label">Code</span><span class="info-value">{code}</span></div>
      </div>
      <button class="btn-close" onclick="closeRoom()">Close Connection</button>
      <div id="closed-msg">Connection closed.</div>
    </div>

    <div class="status-row">
      <span><span class="{atem_dot}" id="atem-dot"></span>Atem</span>
      <span><span class="{astation_dot}" id="astation-dot"></span>Astation</span>
    </div>
  </div>

  <script>
    var CODE = {code_json};
    var pollTimer = null;

    function setDot(id, on) {{
      var el = document.getElementById(id);
      if (on) el.classList.add('connected'); else el.classList.remove('connected');
    }}

    function showExpired() {{
      document.getElementById('card').classList.add('expired');
      document.getElementById('expired-msg').style.display = 'block';
      document.getElementById('view-waiting').style.display = 'block';
      clearTimeout(pollTimer);
    }}

    function showPaired(data) {{
      document.getElementById('view-waiting').style.display = 'none';
      document.getElementById('view-paired').style.display = 'block';
      document.getElementById('paired-hostname').textContent = data.hostname || '—';
      clearTimeout(pollTimer);
    }}

    function showWaiting() {{
      document.getElementById('view-waiting').style.display = 'block';
      document.getElementById('view-paired').style.display = 'none';
    }}

    async function poll() {{
      try {{
        var resp = await fetch('/api/pair/' + CODE);
        if (resp.status === 404) {{ showExpired(); return; }}
        var data = await resp.json();
        setDot('atem-dot', data.atem_connected);
        setDot('astation-dot', data.astation_connected);
        if (data.expired) {{ showExpired(); return; }}
        if (data.paired) {{ showPaired(data); return; }}
        showWaiting();
        pollTimer = setTimeout(poll, 2000);
      }} catch(e) {{
        pollTimer = setTimeout(poll, 5000);
      }}
    }}

    async function closeRoom() {{
      try {{
        await fetch('/api/pair/' + CODE, {{ method: 'DELETE' }});
      }} catch(e) {{}}
      document.getElementById('closed-msg').style.display = 'block';
      document.querySelector('.btn-close').style.display = 'none';
    }}

    poll();
  </script>
</body>
</html>"#,
        code = code_esc,
        hostname = hostname_esc,
        code_url = code_url,
        code_json = serde_json::to_string(code).unwrap_or_else(|_| format!("\"{}\"", code_esc)),
        expired_class = expired_class,
        atem_dot = atem_dot,
        astation_dot = astation_dot,
    )
}

#[cfg(test)]
mod tests {
    use crate::voice_session::VoiceSessionStore;
    use super::*;
    use crate::session_verify::SessionVerifyCache;

    #[test]
    fn pairing_code_format() {
        let code = generate_pairing_code();
        assert_eq!(code.len(), 9); // 4 + '-' + 4
        assert_eq!(&code[4..5], "-");

        // No ambiguous characters
        let no_hyphen = code.replace('-', "");
        for ch in no_hyphen.chars() {
            assert!(
                CODE_CHARS.contains(&(ch as u8)),
                "Character '{}' should be in CODE_CHARS",
                ch
            );
        }
    }

    #[test]
    fn pairing_code_uniqueness() {
        let codes: Vec<String> = (0..20).map(|_| generate_pairing_code()).collect();
        let unique: std::collections::HashSet<&String> = codes.iter().collect();
        assert!(unique.len() > 1, "Pairing codes should vary");
    }

    #[test]
    fn pairing_code_no_ambiguous_chars() {
        for _ in 0..100 {
            let code = generate_pairing_code();
            let no_hyphen = code.replace('-', "");
            assert!(!no_hyphen.contains('0'), "Should not contain 0");
            assert!(!no_hyphen.contains('O'), "Should not contain O");
            assert!(!no_hyphen.contains('1'), "Should not contain 1");
            assert!(!no_hyphen.contains('I'), "Should not contain I");
            assert!(!no_hyphen.contains('L'), "Should not contain L");
        }
    }

    #[tokio::test]
    async fn relay_hub_create_and_lookup() {
        let hub = RelayHub::new();

        let room = PairRoom {
            code: "ABCD-EFGH".to_string(),
            hostname: "test-host".to_string(),
            atem_txs: HashMap::new(),
            astation_tx: None,
            created_at: Instant::now(),
        };

        hub.rooms
            .write()
            .await
            .insert("ABCD-EFGH".to_string(), room);

        let rooms = hub.rooms.read().await;
        assert!(rooms.contains_key("ABCD-EFGH"));
        assert_eq!(rooms["ABCD-EFGH"].hostname, "test-host");
    }

    #[tokio::test]
    async fn relay_hub_cleanup_expired() {
        let hub = RelayHub::new();

        // Create a room with a very old timestamp
        let room = PairRoom {
            code: "OLD1-CODE".to_string(),
            hostname: "old-host".to_string(),
            atem_txs: HashMap::new(),
            astation_tx: None,
            created_at: Instant::now() - std::time::Duration::from_secs(ROOM_EXPIRY_SECS + 10),
        };
        hub.rooms
            .write()
            .await
            .insert("OLD1-CODE".to_string(), room);

        // Create a fresh room
        let fresh = PairRoom {
            code: "NEW1-CODE".to_string(),
            hostname: "new-host".to_string(),
            atem_txs: HashMap::new(),
            astation_tx: None,
            created_at: Instant::now(),
        };
        hub.rooms
            .write()
            .await
            .insert("NEW1-CODE".to_string(), fresh);

        hub.cleanup_expired().await;

        let rooms = hub.rooms.read().await;
        assert!(!rooms.contains_key("OLD1-CODE"), "Expired room should be removed");
        assert!(rooms.contains_key("NEW1-CODE"), "Fresh room should remain");
    }

    #[tokio::test]
    async fn relay_hub_cleanup_keeps_paired() {
        let hub = RelayHub::new();

        // Create an old but paired room (astation_tx is Some)
        let (tx, _rx) = mpsc::unbounded_channel::<String>();
        let room = PairRoom {
            code: "PAIR-CODE".to_string(),
            hostname: "paired-host".to_string(),
            atem_txs: HashMap::new(),
            astation_tx: Some(tx),
            created_at: Instant::now() - std::time::Duration::from_secs(ROOM_EXPIRY_SECS + 10),
        };
        hub.rooms
            .write()
            .await
            .insert("PAIR-CODE".to_string(), room);

        hub.cleanup_expired().await;

        let rooms = hub.rooms.read().await;
        assert!(
            rooms.contains_key("PAIR-CODE"),
            "Paired room should not be cleaned up"
        );
    }

    fn default_status() -> InitialPageStatus {
        InitialPageStatus { atem_connected: false, astation_connected: false, expired: false }
    }

    #[test]
    fn render_pair_page_contains_code() {
        let html = render_pair_page("TEST-CODE", "my-host", &default_status());
        assert!(html.contains("TEST-CODE"));
        assert!(html.contains("my-host"));
        assert!(html.contains("astation://pair?code=TEST-CODE"));
    }

    // --- Integration tests (HTTP endpoint tests) ---

    use axum::{
        body::Body,
        http::{Request, StatusCode as HttpStatusCode},
        Router,
    };
    use tower::ServiceExt;

    fn create_relay_app() -> Router {
        let state = crate::AppState {
            sessions: crate::session_store::SessionStore::new(),
            relay: RelayHub::new(),
            rtc_sessions: crate::rtc_session::RtcSessionStore::new(),
            session_verify_cache: SessionVerifyCache::new(),
            voice_sessions: VoiceSessionStore::new(),
        };
        Router::new()
            .route("/api/pair", axum::routing::post(create_pair_handler))
            .route("/api/pair/:code", axum::routing::get(pair_status_handler).delete(delete_pair_handler))
            .route("/ws", axum::routing::get(ws_handler))
            .route("/pair", axum::routing::get(pair_page_handler))
            .with_state(state)
    }

    /// Helper: POST /api/pair with given hostname, returns the response body as CreatePairResponse.
    async fn post_create_pair(app: Router, hostname: &str) -> (HttpStatusCode, String) {
        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/api/pair")
                    .header("Content-Type", "application/json")
                    .body(Body::from(format!(r#"{{"hostname": "{}"}}"#, hostname)))
                    .unwrap(),
            )
            .await
            .unwrap();
        let status = response.status();
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let body_str = String::from_utf8(body.to_vec()).unwrap();
        (status, body_str)
    }

    #[tokio::test]
    async fn test_create_pair_endpoint() {
        let app = create_relay_app();
        let (status, body_str) = post_create_pair(app, "my-machine").await;

        assert_eq!(status, HttpStatusCode::CREATED);

        let resp: CreatePairResponse = serde_json::from_str(&body_str).unwrap();
        // Code should be in XXXX-XXXX format (9 chars total)
        assert_eq!(resp.code.len(), 9, "Code should be 9 characters (XXXX-XXXX)");
        assert_eq!(
            &resp.code[4..5],
            "-",
            "Code should have hyphen at position 4"
        );
        // Each half should be 4 alphanumeric chars
        let left = &resp.code[..4];
        let right = &resp.code[5..];
        assert!(
            left.chars().all(|c| c.is_ascii_alphanumeric()),
            "Left half should be alphanumeric"
        );
        assert!(
            right.chars().all(|c| c.is_ascii_alphanumeric()),
            "Right half should be alphanumeric"
        );
    }

    #[tokio::test]
    async fn test_create_pair_code_no_ambiguous_chars() {
        // Create several pairs and verify none contain ambiguous characters
        for _ in 0..20 {
            let app = create_relay_app();
            let (status, body_str) = post_create_pair(app, "test-host").await;
            assert_eq!(status, HttpStatusCode::CREATED);

            let resp: CreatePairResponse = serde_json::from_str(&body_str).unwrap();
            let code_no_hyphen = resp.code.replace('-', "");
            assert!(
                !code_no_hyphen.contains('0'),
                "Code should not contain '0': {}",
                resp.code
            );
            assert!(
                !code_no_hyphen.contains('O'),
                "Code should not contain 'O': {}",
                resp.code
            );
            assert!(
                !code_no_hyphen.contains('1'),
                "Code should not contain '1': {}",
                resp.code
            );
            assert!(
                !code_no_hyphen.contains('I'),
                "Code should not contain 'I': {}",
                resp.code
            );
            assert!(
                !code_no_hyphen.contains('L'),
                "Code should not contain 'L': {}",
                resp.code
            );
        }
    }

    #[tokio::test]
    async fn test_pair_status_exists() {
        let app = create_relay_app();

        // Step 1: Create a pair
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/api/pair")
                    .header("Content-Type", "application/json")
                    .body(Body::from(r#"{"hostname": "dev-machine"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::CREATED);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let created: CreatePairResponse = serde_json::from_slice(&body).unwrap();
        let code = created.code;

        // Step 2: GET /api/pair/:code should return paired=false
        let response = app
            .oneshot(
                Request::builder()
                    .uri(format!("/api/pair/{}", code))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::OK);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let status_resp: PairStatusResponse = serde_json::from_slice(&body).unwrap();
        assert!(!status_resp.paired, "Newly created pair should not be paired yet");
        assert_eq!(status_resp.hostname, "dev-machine");
    }

    #[tokio::test]
    async fn test_pair_status_not_found() {
        let app = create_relay_app();

        let response = app
            .oneshot(
                Request::builder()
                    .uri("/api/pair/NONEXIST")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn test_pair_page_exists() {
        let app = create_relay_app();

        // Step 1: Create a pair
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/api/pair")
                    .header("Content-Type", "application/json")
                    .body(Body::from(r#"{"hostname": "page-test-host"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::CREATED);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let created: CreatePairResponse = serde_json::from_slice(&body).unwrap();
        let code = created.code;

        // Step 2: GET /pair?code=XXXX should return HTML containing the code
        let response = app
            .oneshot(
                Request::builder()
                    .uri(format!("/pair?code={}", code))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::OK);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let html = String::from_utf8(body.to_vec()).unwrap();
        assert!(
            html.contains(&code),
            "HTML page should contain the pairing code"
        );
        assert!(
            html.contains("page-test-host"),
            "HTML page should contain the hostname"
        );
        assert!(
            html.contains("Atem Pairing"),
            "HTML page should contain the page title"
        );
        assert!(
            html.contains(&format!("astation://pair?code={}", code)),
            "HTML page should contain the deep link"
        );
    }

    #[tokio::test]
    async fn test_pair_page_not_found() {
        let app = create_relay_app();

        let response = app
            .oneshot(
                Request::builder()
                    .uri("/pair?code=NONEXIST")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::NOT_FOUND);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let html = String::from_utf8(body.to_vec()).unwrap();
        assert!(
            html.contains("not found"),
            "404 page should indicate code not found"
        );
    }

    #[tokio::test]
    async fn test_ws_handler_room_not_found() {
        let app = create_relay_app();

        // Send a non-upgrade GET request to /ws with a nonexistent room code.
        // Without the WebSocket upgrade headers, the handler should check the room
        // and return 404 before attempting the upgrade.
        let response = app
            .oneshot(
                Request::builder()
                    .uri("/ws?role=atem&code=NONEXIST")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        // The ws_handler checks room existence before upgrade, so a non-upgrade
        // request to a nonexistent room should still fail. Axum returns 400 for
        // missing upgrade headers on WebSocket routes when the handler calls
        // ws.on_upgrade(), but our handler returns 404 before reaching that point
        // for nonexistent rooms.
        // Note: Since the request lacks upgrade headers, axum's WebSocketUpgrade
        // extractor will reject it. The handler won't even run. Axum returns 400
        // or the rejection status. We verify it does NOT return 200/101.
        let status = response.status();
        assert!(
            status == HttpStatusCode::NOT_FOUND
                || status == HttpStatusCode::BAD_REQUEST
                || status == HttpStatusCode::UPGRADE_REQUIRED,
            "Expected 404, 400, or 426 for non-upgrade WS request to nonexistent room, got {}",
            status
        );
    }

    #[tokio::test]
    async fn test_create_multiple_pairs_unique_codes() {
        let app = create_relay_app();
        let mut codes = std::collections::HashSet::new();

        for i in 0..10 {
            let response = app
                .clone()
                .oneshot(
                    Request::builder()
                        .method("POST")
                        .uri("/api/pair")
                        .header("Content-Type", "application/json")
                        .body(Body::from(format!(r#"{{"hostname": "host-{}"}}"#, i)))
                        .unwrap(),
                )
                .await
                .unwrap();

            assert_eq!(response.status(), HttpStatusCode::CREATED);
            let body = axum::body::to_bytes(response.into_body(), usize::MAX)
                .await
                .unwrap();
            let resp: CreatePairResponse = serde_json::from_slice(&body).unwrap();
            codes.insert(resp.code);
        }

        assert_eq!(
            codes.len(),
            10,
            "All 10 pairing codes should be unique"
        );
    }

    #[tokio::test]
    async fn test_pairing_code_entropy() {
        // Generate many codes to verify randomness distribution
        let mut first_chars = std::collections::HashMap::new();
        for _ in 0..100 {
            let code = generate_pairing_code();
            let first_char = code.chars().next().unwrap();
            *first_chars.entry(first_char).or_insert(0) += 1;
        }

        // Should have reasonable distribution (at least 5 different first characters out of 100 samples)
        assert!(
            first_chars.len() >= 5,
            "Pairing codes should have good entropy, got {} unique first chars",
            first_chars.len()
        );
    }

    #[tokio::test]
    async fn test_pair_page_xss_protection() {
        // Test that hostname with HTML/JS is safely escaped
        let html = render_pair_page("TEST-CODE", "<script>alert('xss')</script>", &default_status());
        // If properly escaped, the literal string should appear, not executed
        assert!(!html.contains("<script>alert"), "Script tags should be escaped or removed");

        // Test with other XSS vectors
        let html2 = render_pair_page("CODE-123", "' onload='alert(1)'", &default_status());
        assert!(!html2.contains("onload='alert"), "Event handlers should be escaped");
    }

    #[tokio::test]
    async fn test_cleanup_expired_keeps_recently_paired() {
        let hub = RelayHub::new();

        // Create an old room but with atem connected (not astation)
        let (tx_atem, _rx) = mpsc::unbounded_channel::<String>();
        let mut old_atem_txs = HashMap::new();
        old_atem_txs.insert("test-atem".to_string(), tx_atem);
        let room = PairRoom {
            code: "OLD-ATEM".to_string(),
            hostname: "old-host".to_string(),
            atem_txs: old_atem_txs,
            astation_tx: None,
            created_at: Instant::now() - std::time::Duration::from_secs(ROOM_EXPIRY_SECS + 10),
        };
        hub.rooms.write().await.insert("OLD-ATEM".to_string(), room);

        hub.cleanup_expired().await;

        let rooms = hub.rooms.read().await;
        // Should be removed (only astation_tx prevents cleanup)
        assert!(!rooms.contains_key("OLD-ATEM"), "Room with only atem connected should be cleaned up");
    }

    #[tokio::test]
    async fn test_pair_status_shows_unpaired_then_paired() {
        let state = crate::AppState {
            sessions: crate::session_store::SessionStore::new(),
            relay: RelayHub::new(),
            rtc_sessions: crate::rtc_session::RtcSessionStore::new(),
            session_verify_cache: SessionVerifyCache::new(),
            voice_sessions: VoiceSessionStore::new(),
        };

        // Create pair
        let code = generate_pairing_code();
        let room = PairRoom {
            code: code.clone(),
            hostname: "test-host".to_string(),
            atem_txs: HashMap::new(),
            astation_tx: None,
            created_at: Instant::now(),
        };
        state.relay.rooms.write().await.insert(code.clone(), room);

        let app = Router::new()
            .route("/api/pair/:code", axum::routing::get(pair_status_handler))
            .with_state(state.clone());

        // Check status before pairing
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .uri(format!("/api/pair/{}", code))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), HttpStatusCode::OK);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let status: PairStatusResponse = serde_json::from_slice(&body).unwrap();
        assert!(!status.paired, "Should not be paired initially");

        // Simulate both sides connecting
        let (tx_astation, _rx) = mpsc::unbounded_channel::<String>();
        let (tx_atem, _rx2) = mpsc::unbounded_channel::<String>();
        {
            let mut rooms = state.relay.rooms.write().await;
            if let Some(room) = rooms.get_mut(&code) {
                room.astation_tx = Some(tx_astation);
                room.atem_txs.insert("test-atem".to_string(), tx_atem);
            }
        }

        // Check status after both connected
        let app2 = Router::new()
            .route("/api/pair/:code", axum::routing::get(pair_status_handler))
            .with_state(state);

        let response = app2
            .oneshot(
                Request::builder()
                    .uri(format!("/api/pair/{}", code))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let status: PairStatusResponse = serde_json::from_slice(&body).unwrap();
        assert!(status.paired, "Should be paired after both sides connect");
        assert!(status.astation_connected);
        assert!(status.atem_connected);
    }

    #[tokio::test]
    async fn test_concurrent_pair_creation() {
        use std::sync::Arc;
        use tokio::sync::Mutex;

        let app = Arc::new(Mutex::new(create_relay_app()));
        let mut handles = Vec::new();

        for i in 0..10 {
            let app_clone = app.clone();
            handles.push(tokio::spawn(async move {
                let app = app_clone.lock().await;
                let response = app
                    .clone()
                    .oneshot(
                        Request::builder()
                            .method("POST")
                            .uri("/api/pair")
                            .header("Content-Type", "application/json")
                            .body(Body::from(format!(r#"{{"hostname": "host-{}"}}"#, i)))
                            .unwrap(),
                    )
                    .await
                    .unwrap();

                let body = axum::body::to_bytes(response.into_body(), usize::MAX)
                    .await
                    .unwrap();
                serde_json::from_slice::<CreatePairResponse>(&body)
                    .ok()
                    .map(|r| r.code)
            }));
        }

        let mut codes = std::collections::HashSet::new();
        for handle in handles {
            if let Some(code) = handle.await.unwrap() {
                codes.insert(code);
            }
        }

        assert_eq!(codes.len(), 10, "All concurrent pairs should have unique codes");
    }

    #[test]
    fn test_code_chars_does_not_contain_ambiguous() {
        let chars_str = String::from_utf8_lossy(CODE_CHARS);
        assert!(!chars_str.contains('0'), "CODE_CHARS should not contain 0");
        assert!(!chars_str.contains('O'), "CODE_CHARS should not contain O");
        assert!(!chars_str.contains('1'), "CODE_CHARS should not contain 1");
        assert!(!chars_str.contains('I'), "CODE_CHARS should not contain I");
        assert!(!chars_str.contains('L'), "CODE_CHARS should not contain L");
    }
}
